server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cafe?allowpublickeyretrieval=true&usessl=false&serverTimezone=Asia/Seoul
    #url: jdbc:mysql://fourman-db/db_cafe?allowpublickeyretrieval=true&usessl=false&serverTimezone=Asia/Seoul
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      repositories:
        enabled: false

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  cache:
    type: redis

  redis:
    host: 127.0.0.1
    #host: redis
    port: 6379
    username: default
    password: qwer1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true